### ISSUE TITLE
Conda install needs specific Python version to work

### ISSUE THREAD

**Issue by qin-yu** [hci-unihd/plant-seg#122] opened 2022-12-14 21:45 UTC
Hey Lorenzo, it looks like Python 3.9 plant-seg installation causes runtime errors, which can be fixed by setting `python=3.8` for now. 

```bash
$ conda create -n plant-seg-3.8 -c pytorch -c conda-forge -c lcerrone -c awolny python=3.8 pytorch=1.9 pytorch-3dunet=1.3.7 plantseg
```

If I use the current installation command, then running segmentation with plant-seg gives error:
```bash
ImportError: ~/miniconda3/envs/plant-seg/lib/python3.9/site-packages/vigra/../../../libemon.so.1.3.1: undefined symbol: _ZN8ClpModel13setColumnNameEiRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by lorenzocerrone** [comment] 2022-12-19 10:21
Hi Qin,  I close this because it's a duplicate of #120.

But thanks!  I will patch the installation instructions before we release the new version

**Closed by lorenzocerrone** 2022-12-19 10:21 UTC
