### ISSUE TITLE
No instructions for how to do proofreading

### ISSUE THREAD

**Issue by Buglakova** [hci-unihd/plant-seg#188] opened 2024-02-05 12:38 UTC
Hello,

I tried to use both the new proofreading tool in napari and the old proofreading tool from [`plant-seg-tools`](https://github.com/hci-unihd/plant-seg-tools) but I could not find any instructions on how to use either. A description of the expected workflow, list of hot keys and a couple of short videos would be very helpful.

**Comment by qin-yu** [comment] 2024-02-05 18:02
Duplicate of #177 

Thanks Alyona! Lorenzo has been fixing this (short videos with description for key functionalities).

**Closed by qin-yu** 2024-02-05 18:02 UTC
Labels: duplicate
